### ISSUE TITLE
关于 dt

### ISSUE THREAD

**Issue by seisman** [wangliang1989/oh-my-cap#17]
共三个地方涉及到了 dt：
1. 格林函数
2. 数据
3. `cap.pl` 的 `-H` 选项

需要做的是：
1. 确认三个 dt 是否一定要相等
2. 若1成立，则修改源码使得其检测这一条件是否成立

**Comment by wangliang1989** [comment]
确认在代码里都是0.2Hz，数据会重采样为0.2Hz。
至于三个dt是否要相等，这个格林函数和数据必须一致，是 Prof. ZhengYong 说的，其余不知

**Comment by wangliang1989** [comment]
检测的方式打算为在反演时，根据将调用cap.pl的H参数来检测(saclst)格林函数和数据
