### ISSUE TITLE
SAC 文件名、权重文件的协调问题

### ISSUE THREAD

**Issue by wangliang1989** [wangliang1989/oh-my-cap#31]
在反演时，是权重文件中的台名+分量来搜索sac文件的，对此要考虑有loc的时候，文件名协调的问题

**Comment by wangliang1989** [comment]
finished in #32

**Comment by zhang0709-stu** [comment]
在反演时，perl inversion.pl 20080418093658 报错 ：20080418093658/ 5 1
Error in reading SAC header 1
fail to read in source time: 1
