### ISSUE TITLE
确定例子事件

### ISSUE THREAD

**Issue by wangliang1989** [wangliang1989/oh-my-cap#4]
根据 gCAP 的官方版本中包含的例子中的sac文件的事件时间和经纬度信息，基本确认该事件是 IRIS 上的 [2725882](http://ds.iris.edu/ds/nodes/dmc/tools/event/2725882)事件，但相关信息并不完全一致，请@seisman 确认

**Comment by seisman** [comment]
地震目录是会不断更新的，gcap中的示例的事件信息与IRIS上的事件信息差别小，确认是同一个地震事件。
