### ISSUE TITLE
请教：计算单力源和爆炸型震源时，程序报错。

### ISSUE THREAD

**Issue by zj023** [wangliang1989/oh-my-cap#52]
请教一个问题：计算单力源和爆炸型震源时，程序报错。非常感谢！
命令行为：$ fk.pl -Mhk/15/k -N1024/0.1 -S0 -U0 10。（计算爆炸型震源时）。   程序默认的-S2（双力偶型震源）
报错：Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
Backtrace for this error:
#0  0x7f8eac02532a
#1  0x7f8eac024503
#2  0x7f8eab8b9fcf
#3  0x559541734f9f
#4  0x559541734922
#5  0x5595417329db
#6  0x55954173380b
#7  0x7f8eab89cb96
#8  0x5595417313e9
#9  0xffffffffffffffff
hk_15/10.grn.0
Unable to open hk_15/10.grn.0
hk_15/10.grn.5
Unable to open hk_15/10.grn.5

**Comment by wangliang1989** [comment]
什么操作系统？

**Comment by zj023** [comment]
前辈您好！我用的ubuntu-18 &nbsp;64位。我给您的邮箱wangliang0222@foxmail.com发了一封邮件。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangliang1989/oh-my-cap"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月23日(星期三) 中午1:07
收件人:&nbsp;"wangliang1989/oh-my-cap"<oh-my-cap@noreply.github.com&gt;;
抄送:&nbsp;"happy boy?"<1551010469@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wangliang1989/oh-my-cap] 请教：计算单力源和爆炸型震源时，程序报错。 (#52)





 
什么操作系统？

**Comment by zj023** [comment]
另外我使用的是fk3.3版本。

**Comment by Jinyin-Hu** [comment]
您好，请问这个报错是怎么解决的？我也遇到同样的问题，谢谢。

**Comment by zj023** [comment]
我当时没整出来，现在没做这个行业咯。




happy&nbsp;boy?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangliang1989/oh-my-cap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月6日(星期三) 下午3:05
***@***.***&gt;;
抄送:&nbsp;"happy ***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangliang1989/oh-my-cap] 请教：计算单力源和爆炸型震源时，程序报错。 (#52)





 
您好，请问这个报错是怎么解决的？我也遇到同样的问题，谢谢。
