### ISSUE TITLE
gcap安装

### ISSUE THREAD

**Issue by Ma-yuan-science** [wangliang1989/oh-my-cap#55]
老师您好，我是用里面的gcap时一直有问题
#报错：can‘t exec 'cap.pl':NO such...
请问是gcc要降到3.4版本的吗
另外，请问咱们是否有qq群这样的交流平台大家可以方便交流

**Comment by wangliang1989** [comment]
不是，是你的环境变量没有设置成功

没有QQ群

**Comment by Ma-yuan-science** [comment]
谢谢您
